### ISSUE TITLE
TeaCache for the Flow matching part to accelerate it 2x+

### ISSUE THREAD

**Issue by kabachuha** [ByteDance-Seed/Bagel#37]
As the model uses Flow matching for decoding, it's theoretically possible to integrate TeaCache into it and get ~2x speedup.

TeaCache is opensourced and has a paper https://github.com/ali-vilab/TeaCache

Although, it its written about the timestep embedding there, the inputs in principle can be the bare input values as well

Currently, a generation of a picture takes 5 minutes on my single 4090, and it will much help to accelerate the process

**Comment by eugene-kamenev** [comment]
https://github.com/eugene-kamenev/BagelUI-TeaCache

I did some work on this, got 4x+ gain in generation speeds for Bagel, now it is super good/fast for prototyping or testing prompts.

### TeaCache Bagel Implementation Test

**Inference Parameters:**

```yaml
seed: 1234
thinking: false
cfg_text_scale: 4
cfg_image_scale: 2
cfg_interval: 0
cfg_renorm_type: text_channel
cfg_renorm_min: 0
timesteps: 50
timestep_shift: 3
```

**Prompt:**
She boards a modern subway, quietly reading a folded newspaper, wearing the same clothes.

| Setting           | Denoising Time | Skipped Steps | Result |
|-------------------|----------------|---------------|--------|
| TeaCache disabled | 00:51<00:00,  1.06it/s         |     0     | <img src="https://github.com/user-attachments/assets/efad65d7-829f-4a40-a1a3-f67068c7f4cf" width="137" height="175"> |
| TeaCache (thrs=0.1, warmup_steps=2)      | 00:51<00:00,  1.06it/s         |     0     | <img src="https://github.com/user-attachments/assets/ec0fa727-88cd-481e-a34f-2783ba264359" width="137" height="175"> |
| TeaCache (thrs=0.2, warmup_steps=2)      | 00:37<00:00,  1.29it/s         |     13     | <img src="https://github.com/user-attachments/assets/6e565f54-6abc-4b3c-81c3-ba517cd5fcca" width="137" height="175"> |
| TeaCache (thrs=0.3, warmup_steps=2)      | 00:26<00:00,  1.86it/s         |     24     | <img src="https://github.com/user-attachments/assets/86f45f04-af6c-465a-a3ea-b0be2bb26f30" width="137" height="175"> |
| TeaCache (thrs=0.4, warmup_steps=2)      | 00:22<00:00,  2.22it/s         |     28     | <img src="https://github.com/user-attachments/assets/7eb18d6e-8704-486f-bf93-7ed672a05ce6" width="137" height="175"> |
| TeaCache (thrs=0.5, warmup_steps=2)      | 00:17<00:00,  2.74it/s         |     32     | <img src="https://github.com/user-attachments/assets/76d44f79-47eb-4285-a628-3039f55a9066" width="137" height="175"> |
| TeaCache (thrs=0.6, warmup_steps=2)      | 00:15<00:00,  3.11it/s         |     34     |  <img src="https://github.com/user-attachments/assets/f03fc774-e8a1-4018-bbbc-e3a550722782" width="137" height="175"> |
| TeaCache (thrs=0.7, warmup_steps=2)      | 00:13<00:00,  3.60it/s         |     36     | <img src="https://github.com/user-attachments/assets/f0104ce7-8dae-4f15-b358-85d900879302" width="137" height="175"> |
| TeaCache (thrs=0.8, warmup_steps=2)      | 00:12<00:00,  3.90it/s         |     37     | <img src="https://github.com/user-attachments/assets/3750595d-906f-4854-bd25-ac3fe7df2a56" width="137" height="175"> |
| TeaCache (thrs=0.9, warmup_steps=2)      | 00:11<00:00,  4.24it/s         |     38     | <img src="https://github.com/user-attachments/assets/7a9de052-6454-44ab-bb5f-93ce3a3e47af" width="137" height="175"> |
| TeaCache (thrs=1.0, warmup_steps=2)      | 00:10<00:00,  4.67it/s         |     39     |  <img src="https://github.com/user-attachments/assets/25dc8c19-6ddd-43e1-aae2-ee3b56433c08" width="137" height="175"> |

**Comment by eugene-kamenev** [comment]
I also moved VAE to GPU and reduced some pre/post processing steps timing from about 6s to 0.15s. Removed some explicit type conversions float32->bfloat16 etc. One more thing, I disabled sampling in AutoEncoder. Images look different now, but I think mostly because of different seed due to GPU. I also think texts are rendered much better now in my tests (still not great in many cases):

```yaml
seed: 1234
prompt: She holds a paper in hands with words: "PLEASE MAKE BAGEL RENDER ME FASTER"
cfg_image_scale: 2
cfg_text_scale: 5
cfg_interval: 0.6
cfg_renorm_min: 0
timestep_shift: 3
timesteps: 50
renorm_type: text_channel
teacache: false
thinking: false
```
Result: 00:40<00:00,  1.20it/s

<img src="https://github.com/user-attachments/assets/38c05e60-1654-4a2f-8acc-9b5712bf52eb" width="200">

```yaml
teacache: true
warmup: 5
threshold: 0.6
```
Result: 00:14<00:00,  3.28it/s

<img src="https://github.com/user-attachments/assets/67190981-d899-4ec8-bf72-8cd18adcf874" width="200">

Skipping 32 steps helped to render text correctly.

Same thing I experience for these hyper params:

```yaml
renorm_type: global
cfg_text_scale: 4
teacache: false
```

<img src="https://github.com/user-attachments/assets/c18ef1df-7303-48d4-8689-5b9935c6e46e" width="200">

```yaml
teacache: true
warmup: 5
threshold: 0.6
```

<img src="https://github.com/user-attachments/assets/e601770f-d19e-4d19-865e-639e96258804" width="200">

Given the findings above, was easy to understand that reducing timesteps improves text rendering (at least on my branch).
